(function() {
    "use strict";

    /**
     * Created by Jon on 5/26/2015.
     *
     */

    angular
        .module('taic', [
            'ui.router',
            'ui.bootstrap',

            'LocalStorageModule',

            'taic.tmpls',   // Generated by gulp build

            'taic.services',
            'taic.components',

            'taic.views',
            'taic.views.home'
        ])
        .constant('moment', moment)
        .controller('taicCtrl', TAICCtrl)
        .config(onConfig)
        .run(onStart);

    /* ngInject */
    function TAICCtrl() {

    }

    /* ngInject */
    function onConfig($sceDelegateProvider, $locationProvider, localStorageServiceProvider) {
        $locationProvider.html5Mode(true);

        localStorageServiceProvider
          .setPrefix('taic');

        $sceDelegateProvider.resourceUrlWhitelist(['https://www.youtube.com/embed/*', 'self']);
    }

    /* ngInject */
    function onStart($rootScope, $window) {
        angular.element($window).bind('resize', onResize)

        $rootScope.$on('$stateChangeStart', stateChangeStart);
        $rootScope.$on('$stateChangeSuccess', stateChangeSuccess);
        $rootScope.$on('$stateChangeError', stateChangeError);

        function onResize(event) {
            $rootScope.$broadcast('$resize', $window.innerWidth, $window.innerHeight)
        }

        function stateChangeStart(event, toState) {
            console.log(toState.name + ': Start');
        }

        function stateChangeSuccess(event, toState) {
            console.log(toState.name + ': Success');
        }

        function stateChangeError(event, toState) {
            console.log(toState.name + ': Failed');
        }
    }
})();
